from enum import StrEnum


class ChangeTarget(StrEnum):
    OUTPUT = "OUTPUT"
    SESSION_STATE = "SESSION_STATE"
    PERSISTENT_MEMORY = "PERSISTENT_MEMORY"
    BEHAVIORAL_RULE = "BEHAVIORAL_RULE"
    SKILL = "SKILL"
    PROMPT = "PROMPT"
    TOOL_ROUTING = "TOOL_ROUTING"
    TOOL_DEFINITION = "TOOL_DEFINITION"
    ORCHESTRATION = "ORCHESTRATION"
    MODEL_ADAPTER = "MODEL_ADAPTER"
    MODEL_WEIGHTS = "MODEL_WEIGHTS"
    EVALUATOR = "EVALUATOR"
    RESEARCH_PROCESS = "RESEARCH_PROCESS"
    GOVERNANCE_POLICY = "GOVERNANCE_POLICY"


class LoopClosure(StrEnum):
    HUMAN_IN_LOOP = "HUMAN_IN_LOOP"
    HUMAN_ON_LOOP = "HUMAN_ON_LOOP"
    CLOSED_LOOP = "CLOSED_LOOP"


class PersistenceScope(StrEnum):
    EPHEMERAL_OUTPUT = "EPHEMERAL_OUTPUT"
    RUN_LOCAL = "RUN_LOCAL"
    SESSION_LOCAL = "SESSION_LOCAL"
    CROSS_RUN_MEMORY = "CROSS_RUN_MEMORY"
    PERSISTENT_RULE = "PERSISTENT_RULE"
    PERSISTENT_SKILL = "PERSISTENT_SKILL"
    MODEL_ADAPTER = "MODEL_ADAPTER"
    HARNESS_CODE = "HARNESS_CODE"
    EVALUATOR_POLICY = "EVALUATOR_POLICY"
    GOVERNANCE_POLICY = "GOVERNANCE_POLICY"


class VerificationLevel(StrEnum):
    FORMAL_VERIFIER = "FORMAL_VERIFIER"
    EXECUTION_FEEDBACK = "EXECUTION_FEEDBACK"
    EXTERNAL_EMPIRICAL_MEASUREMENT = "EXTERNAL_EMPIRICAL_MEASUREMENT"
    INDEPENDENT_DETERMINISTIC_CHECK = "INDEPENDENT_DETERMINISTIC_CHECK"
    INDEPENDENT_LEARNED_JUDGE = "INDEPENDENT_LEARNED_JUDGE"
    RUBRIC_JUDGE = "RUBRIC_JUDGE"
    CROSS_MODEL_AGREEMENT = "CROSS_MODEL_AGREEMENT"
    SELF_CRITIQUE = "SELF_CRITIQUE"
    SELF_CONSISTENCY = "SELF_CONSISTENCY"
    MODEL_CONFIDENCE = "MODEL_CONFIDENCE"
    MODEL_LIKELIHOOD = "MODEL_LIKELIHOOD"


AUTHORITATIVE_VERIFICATION_LEVELS: frozenset[VerificationLevel] = frozenset(
    {
        VerificationLevel.FORMAL_VERIFIER,
        VerificationLevel.EXECUTION_FEEDBACK,
        VerificationLevel.EXTERNAL_EMPIRICAL_MEASUREMENT,
        VerificationLevel.INDEPENDENT_DETERMINISTIC_CHECK,
        VerificationLevel.INDEPENDENT_LEARNED_JUDGE,
    }
)


def is_authoritative_verification(level: VerificationLevel) -> bool:
    return level in AUTHORITATIVE_VERIFICATION_LEVELS


class ExternalGrounding(StrEnum):
    HUMAN_JUDGMENT = "HUMAN_JUDGMENT"
    PRIMARY_SOURCE = "PRIMARY_SOURCE"
    REAL_WORLD_OBSERVATION = "REAL_WORLD_OBSERVATION"
    CONTROLLED_EXPERIMENT = "CONTROLLED_EXPERIMENT"
    FORMAL_SYSTEM = "FORMAL_SYSTEM"
    INDEPENDENT_TEST_SUITE = "INDEPENDENT_TEST_SUITE"
    EXTERNAL_BENCHMARK = "EXTERNAL_BENCHMARK"
    INDEPENDENT_MODEL = "INDEPENDENT_MODEL"
    PHYSICAL_CONSTRAINT = "PHYSICAL_CONSTRAINT"
    NONE = "NONE"


class ImprovementSignal(StrEnum):
    INTRINSIC_GENERATIVE_DEMONSTRATION = "INTRINSIC_GENERATIVE_DEMONSTRATION"
    INTRINSIC_EVALUATIVE_FEEDBACK = "INTRINSIC_EVALUATIVE_FEEDBACK"
    EXTRINSIC_GROUNDED_EXPERIENCE = "EXTRINSIC_GROUNDED_EXPERIENCE"
    EXTRINSIC_SIMULATED_EXPERIENCE = "EXTRINSIC_SIMULATED_EXPERIENCE"
    HUMAN_CORRECTION = "HUMAN_CORRECTION"
    FORMAL_VERIFICATION = "FORMAL_VERIFICATION"
    EXECUTION_FEEDBACK = "EXECUTION_FEEDBACK"
    EMPIRICAL_MEASUREMENT = "EMPIRICAL_MEASUREMENT"
