"""Strict contracts and deterministic validation for source-bound evidence trails."""

from super_scientist.domain.evidence_trails.models import (
    AssessmentCategory,
    CausalSupport,
    ClaimModality,
    ConstructionMethod,
    EvidenceTrailNode,
    EvidenceTrailRelation,
    EvidenceTrailSnapshot,
    EvidenceTrailVersion,
    ExactSourceSpan,
    RelationType,
    ReportSentenceBinding,
    ReportSourceSpan,
    RetainedEvidenceSource,
    SourceFirstProvenance,
    SourceFirstStageEvent,
    SourceFirstStageKind,
    StructuralLocation,
    StructuralLocationKind,
    TrailAssessment,
    TrailCheckCategory,
    TrailCheckResult,
    TrailGeometry,
    TrailNodeRole,
    TrailOrderingConstraint,
    TrailOutcome,
    TrailValidationInputs,
    TrailValidationResult,
)
from super_scientist.domain.evidence_trails.validation import (
    validate_report_binding,
    validate_trail,
)

__all__ = [
    "AssessmentCategory",
    "CausalSupport",
    "ClaimModality",
    "ConstructionMethod",
    "EvidenceTrailNode",
    "EvidenceTrailRelation",
    "EvidenceTrailSnapshot",
    "EvidenceTrailVersion",
    "ExactSourceSpan",
    "RelationType",
    "ReportSentenceBinding",
    "ReportSourceSpan",
    "RetainedEvidenceSource",
    "SourceFirstProvenance",
    "SourceFirstStageEvent",
    "SourceFirstStageKind",
    "StructuralLocation",
    "StructuralLocationKind",
    "TrailAssessment",
    "TrailCheckCategory",
    "TrailCheckResult",
    "TrailGeometry",
    "TrailNodeRole",
    "TrailOrderingConstraint",
    "TrailOutcome",
    "TrailValidationInputs",
    "TrailValidationResult",
    "validate_report_binding",
    "validate_trail",
]
